spring:
  application:
    name: booking-agent
  config:
    import: optional:secrets-dev.yaml # provides application secrets (passwords, keys, etc)
  datasource:
    url: ''
    username: ''
    password: ''
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  ai:
    openai:
        api-key: ''
        chat:
          options:
            model: gpt-4o
    mcp:
      client:
        enabled: true
        name: mcp-servers
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        stdio:
          servers-configuration: classpath:mcp-servers-config.json
clients:
  weather:
    base-url: https://api.weatherapi.com/v1
    api-key: ''

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.ai.openai: TRACE