spring:
  application:
    name: booking-agent
  config:
    import: optional:secrets-dev.yaml
  ai:
    openai:
      api-key: ''
      chat:
        options:
          model: gpt-4o
    mcp:
      client:
        enabled: true
        name: mcp-servers
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        stdio:
          servers-configuration: classpath:mcp-servers-config.json
    vectorstore:
      chroma:
        initialize-schema: true
        collection-name: booking-agent
        client:
          host: http://localhost
          port: 8000

clients:
  weather:
    base-url: https://api.weatherapi.com/v1
    api-key: ''

logging:
  level:
    org.springframework.ai: TRACE
    org.springframework.ai.openai: TRACE